DROP DATABASE IF EXISTS burgers_DB;
CREATE database burgers_DB;

USE burgers_DB;

CREATE TABLE burgers (
id INTEGER NOT NULL AUTO_INCREMENT,
burger_Name VARCHAR(30) NOT NULL,
devoured BOOLEAN DEFAULT false,
createdAt DATETIME NOT NULL,
updatedAt DATETIME NOT NULL,
PRIMARY KEY (id)


);

